from pathlib import Path


# ============================================================
# APPLICATION SETTINGS
# ============================================================

APP_TITLE = "AI-Powered Customer Retention Intelligence Platform"

PAGE_ICON = "🎯"

LAYOUT = "wide"


# ============================================================
# PROJECT PATHS
# ============================================================

# Dynamically determine the project root.
# This keeps the application portable across different machines.

PROJECT_ROOT = Path(__file__).resolve().parents[2]


# Streamlit application directory

APP_DIR = PROJECT_ROOT / "10_Streamlit_Application"


# ============================================================
# DATA DIRECTORIES
# ============================================================

# Final AI outputs generated by previous project phases

FINAL_DATA_DIR = PROJECT_ROOT / "data" / "final"


# Streamlit application data directories

APP_DATA_DIR = APP_DIR / "data"

SAMPLE_DATA_DIR = APP_DATA_DIR / "sample"

OUTPUT_DATA_DIR = APP_DATA_DIR / "outputs"


# ============================================================
# FINAL AI DATA FILES
# ============================================================

AI_READY_DATA_PATH = (
    FINAL_DATA_DIR / "ai_ready_dataset.csv"
)

AI_CUSTOMER_EXPLANATIONS_PATH = (
    FINAL_DATA_DIR / "ai_customer_explanations.csv"
)

EXECUTIVE_SUMMARY_PATH = (
    FINAL_DATA_DIR / "executive_summary.csv"
)

BUSINESS_REPORT_PATH = (
    FINAL_DATA_DIR / "business_report_data.csv"
)


# ============================================================
# MODEL
# ============================================================

MODEL_DIR = APP_DIR / "models"

MODEL_PATH = MODEL_DIR / "churn_model.pkl"


# ============================================================
# ASSETS
# ============================================================

ASSETS_DIR = APP_DIR / "assets"